include(printOption)
message("==================== Configuration Summary =====================")
message(STATUS "General: ")
message(STATUS "  CMake Version:\t${CMAKE_VERSION}")
message(STATUS "  System:\t${CMAKE_SYSTEM_NAME}")
message(STATUS " ")
message(STATUS "Build: ")
message(STATUS "  C++ Compiler:\t${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "  C++ Standard:\t${CMAKE_CXX_STANDARD}")
message(STATUS "  Build Type:\t${CMAKE_BUILD_TYPE}")
message(STATUS "  Install Prefix:\t${CMAKE_INSTALL_PREFIX}")
message(STATUS "  runtime output directory:\t${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
message(STATUS "  library output directory:\t${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
message(STATUS "  archive output directory:\t${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}")
message(STATUS " ")
message(STATUS "Configuration: ")
prfOption(CP_LIBRARY_CORE)
message(STATUS " ")
message(STATUS "Tests:")
prfOption(CP_TEST)
message(STATUS " ")
message(STATUS "================ Configuration Summary Done =================")

